/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andy_detect_jni_Property */

#ifndef _Included_com_andy_detect_jni_Property
#define _Included_com_andy_detect_jni_Property
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andy_detect_jni_Property
 * Method:    native_get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_detect_jni_Property_native_1get__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_andy_detect_jni_Property
 * Method:    native_get
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_detect_jni_Property_native_1get__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
