/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <sys/system_properties.h>
#include <string.h>

#include "util/log.h"


JNIEXPORT jstring JNICALL Java_com_andy_detect_jni_Property_native_1get__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *env, jclass clazz, jstring keyJ, jstring defJ) {
    int len;

    const char *key;
    char buf[256];
    jstring rvJ = NULL;

    if (keyJ == NULL) {
        LOGI("key must not be null.");
        goto error;
    }

    key = env->GetStringUTFChars(keyJ, NULL);

    len = __system_property_get(key, buf);
    if ((len <= 0) && (defJ != NULL)) {
        rvJ = defJ;
    } else if (len >= 0) {
        rvJ = env->NewStringUTF(buf);
    } else {
        rvJ = env->NewStringUTF("");
    }

    env->ReleaseStringUTFChars(keyJ, key);

error:
    return rvJ;

}

JNIEXPORT jstring JNICALL Java_com_andy_detect_jni_Property_native_1get__Ljava_lang_String_2
  (JNIEnv *env, jclass clazz, jstring keyJ)
{
    return Java_com_andy_detect_jni_Property_native_1get__Ljava_lang_String_2Ljava_lang_String_2(env, clazz, keyJ, NULL);
}
