/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andy_detect_jni_EmulatorDetectUtil */

#ifndef _Included_com_andy_detect_jni_EmulatorDetectUtil
#define _Included_com_andy_detect_jni_EmulatorDetectUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andy_detect_jni_EmulatorDetectUtil
 * Method:    detect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_andy_detect_jni_EmulatorDetectUtil_detect
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
