/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andy_androinfo_jni_TestJni */

#ifndef _Included_com_andy_androinfo_jni_TestJni
#define _Included_com_andy_androinfo_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andy_androinfo_jni_TestJni
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_androinfo_jni_TestJni_getHello__
  (JNIEnv *, jclass);

/*
 * Class:     com_andy_androinfo_jni_TestJni
 * Method:    getHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_androinfo_jni_TestJni_getHello__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
